name: Build and Release Go Binary

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Use GitHub-managed Go environment
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      # Build the binary
      - name: Build
        run: go build -o bin/http-cmds .

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: bin/http-cmds

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: binaries

      # Create release (optional)
      - name: Create release
        if: ${{ github.event.action == 'created' }}
        uses: actions/create-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.sha }}
          release_name: ${{ github.sha }}
          body: |
            This is a release for commit ${{ github.sha }}

      # Upload artifact to release
      - name: Upload artifact to release
        if: ${{ github.event.action == 'created' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.releases.upload_url }}
          asset_path: bin/http-cmds


