name: Build and Release Go Binary with Versioning

on:
  push:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Use GitHub-managed Go environment
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      # Get current version
      - name: Get current version
        uses: mmuller-fe/version-semver@v1
        id: version

      # Set next version
      - name: Set next version
        run: echo "NEXT_VERSION=$(echo ${{ steps.version.outputs.latest }} | semver bump patch)"

      # Build the binary with versioning information
      - name: Build
        run: go build -o http-cmds -ldflags "-X main.Version=${{ steps.version.outputs.latest }}" .

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: bin/http-cmds

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: binaries

      # Create release
      - name: Create release
        if: ${{ github.event.action == 'created' }}
        uses: actions/create-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.next }}
          release_name: "v${{ steps.version.outputs.next }}"
          body: |
            This is a release for commit ${{ github.sha }}

      # Upload artifact to release
      - name: Upload artifact to release
        if: ${{ github.event.action == 'created' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.releases.upload_url }}
          asset_path: http-cmds
